import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Nav from "@/components/Nav";
import Top from "@/components/Top";
import { LoadingProvider } from "@/context/loadingContext";
import "./globals.css";
import localFont from "next/font/local";
import EnergyRecovery from "@/components/updater/EnergyRecovery";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const myFont = localFont({
  src: "./CherryBombOne.ttf",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${myFont.className}  `}>
        <LoadingProvider>
          <div className="container mx-auto max-w-md p-4  bg-custom-bg bg-no-repeat bg-top">
            <Top />
            <EnergyRecovery />
            {children}
            <Nav />
          </div>
        </LoadingProvider>
      </body>
    </html>
  );
}
